services:
  backend:
    build: 
      context: ./backend
    container_name: cognisn_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
    container_name: cognisn_frontend
    ports:
      - "8080:8000"
    volumes:
      - ./frontend:/app
    environment:
      - FASTAPI_URL=http://backend:8000  # Sets the URL dynamically for Docker
    depends_on:
      - backend
    restart: unless-stopped